use serde::Deserialize;
use std::env;
use std::fs;
use std::path::Path;

#[derive(Deserialize, Default)]
struct AppInfo {
    #[serde(rename = "messageKeys", default)]
    message_keys: Vec<String>,
    #[serde(default)]
    resources: Resources,
}

#[derive(Deserialize, Default)]
struct Resources {
    #[serde(default)]
    media: Vec<Media>,
}

#[derive(Deserialize, Default)]
struct Media {
    name: String,
    #[serde(rename = "targetPlatforms", default)]
    target_platforms: Option<Vec<String>>,
}

#[derive(Deserialize, Default)]
struct PackageJson {
    pebble: AppInfo,
}

/// Helper to figure out which Pebble platform feature is currently active
fn get_active_platform() -> String {
    if let Ok(p) = env::var("PEBBLE_PLATFORM") {
        return p.to_lowercase();
    }

    let platforms = [
        "APLITE", "BASALT", "CHALK", "DIORITE", "EMERY", "FLINT", "GABBRO",
    ];
    for platform in platforms {
        if env::var(format!("CARGO_FEATURE_{}", platform)).is_ok() {
            return platform.to_lowercase();
        }
    }

    "emery".to_string()
}

pub fn build() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let out_dir_path = Path::new(&out_dir);

    let current_platform = get_active_platform();

    println!("cargo:rerun-if-changed=package.json");

    let content = fs::read_to_string("package.json").expect("Failed to read package.json");
    let pkg: PackageJson = serde_json::from_str(&content).expect("Invalid package.json");
    let app_info = pkg.pebble;

    // --- Message Keys ---
    let mut msg_code = String::from("// Auto-generated by pebble-build\n\n");

    for (current_msg_id, key) in (10000..).zip(app_info.message_keys.iter()) {
        let safe_key = if key.starts_with("MESSAGE_KEY_") {
            key.clone()
        } else {
            format!("MESSAGE_KEY_{}", key)
        };
        msg_code.push_str(&format!(
            "pub const {}: u32 = {};\n",
            safe_key, current_msg_id
        ));
    }
    fs::write(out_dir_path.join("message_keys.rs"), msg_code).expect("Failed to write keys");

    // --- Resource IDs ---
    let mut res_code = String::from("// Auto-generated by pebble-build\n\n");

    let mut current_res_id = 1;
    for media in &app_info.resources.media {
        if let Some(platforms) = &media.target_platforms
            && !platforms.contains(&current_platform)
        {
            continue;
        }

        let safe_name = if media.name.starts_with("RESOURCE_ID_") {
            media.name.clone()
        } else {
            format!("RESOURCE_ID_{}", media.name)
        };

        res_code.push_str(&format!(
            "pub const {}: u32 = {};\n",
            safe_name, current_res_id
        ));
        current_res_id += 1;
    }
    fs::write(out_dir_path.join("resource_ids.rs"), res_code).expect("Failed to write resources");
}
