use std::env;
use std::fs;
use std::path::Path;

/// Helper to figure out which Pebble platform feature is currently active
fn get_active_platform() -> String {
    if let Ok(p) = env::var("PEBBLE_PLATFORM") {
        return p.to_lowercase();
    }

    let platforms = [
        "APLITE", "BASALT", "CHALK", "DIORITE", "EMERY", "FLINT", "GABBRO",
    ];
    for platform in platforms {
        if env::var(format!("CARGO_FEATURE_{}", platform)).is_ok() {
            return platform.to_lowercase();
        }
    }

    "emery".to_string()
}

/// Call this function from your app's build.rs `main()` function.
pub fn build() {
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_dir_path = Path::new(&out_dir);

    // --- 1. Message Keys Parsing ---
    println!("cargo:rerun-if-changed=build/src/message_keys.auto.c");

    let msg_c_file_path = Path::new("build/src/message_keys.auto.c");
    if !msg_c_file_path.exists() {
        println!("cargo:warning=[BUILD.RS] ERROR: build/src/message_keys.auto.c does not exist!");
        panic!("Missing message_keys.auto.c");
    }

    let msg_content =
        fs::read_to_string(msg_c_file_path).expect("Failed to read message keys C file");
    let mut msg_code = String::from("// Auto-generated by pebble-build from message_keys.auto.c\n\n");

    for line in msg_content.lines() {
        let line = line.trim();
        if line.starts_with("uint32_t MESSAGE_KEY_") {
            let parts: Vec<&str> = line
                .split(&[' ', '=', ';'][..])
                .filter(|s| !s.is_empty())
                .collect();

            if parts.len() >= 3 {
                let key_name = parts[1];
                let key_value = parts[2];
                msg_code.push_str(&format!("pub const {}: u32 = {};\n", key_name, key_value));
            }
        }
    }

    let dest_msg_path = out_dir_path.join("message_keys.rs");
    fs::write(&dest_msg_path, msg_code).expect("Failed to write message_keys.rs");

    // --- 2. Resource IDs Parsing ---
    println!("cargo:rerun-if-changed=package.json");
    println!("cargo:rerun-if-changed=appinfo.json");

    let active_platform = get_active_platform();

    let res_c_file_path = Path::new("build")
        .join(&active_platform)
        .join("src")
        .join("resource_ids.auto.c");

    println!("cargo:rerun-if-changed={}", res_c_file_path.display());

    let mut res_code = String::from("// Auto-generated by pebble-build from resource_ids.auto.c\n\n");

    if res_c_file_path.exists() {
        let res_content =
            fs::read_to_string(&res_c_file_path).expect("Failed to read resource_ids.auto.c");

        for line in res_content.lines() {
            let line = line.trim();
            if line.starts_with("uint32_t RESOURCE_ID_") {
                let parts: Vec<&str> = line
                    .split(&[' ', '=', ';'][..])
                    .filter(|s| !s.is_empty())
                    .collect();

                if parts.len() >= 3 {
                    let key_name = parts[1];
                    let key_value = parts[2];
                    res_code.push_str(&format!("pub const {}: u32 = {};\n", key_name, key_value));
                }
            }
        }
    } else {
        println!(
            "cargo:warning=[BUILD.RS] {} not found. Ensure 'pebble build' generated it.",
            res_c_file_path.display()
        );
    }

    let dest_res_path = out_dir_path.join("resource_ids.rs");
    fs::write(&dest_res_path, res_code).expect("Failed to write resource_ids.rs");
}
