[package]
name = "hello-world"
version = "0.1.0"
authors = ["RoccoDev <roccodev.business@gmail.com>"]
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
pebble-rs = {path = "../../pebble-rs" }
pebble-sys = {path = "../../pebble-sys" }

[build-dependencies]
pebble-build = { path = "../../pebble-build" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[features]
default = ["emery"]

aplite = ["pebble-rs/aplite"]
basalt = ["pebble-rs/basalt"]
chalk = ["pebble-rs/chalk"]
diorite = ["pebble-rs/diorite"]
emery = ["pebble-rs/emery"]
flint = ["pebble-rs/flint"]
gabbro = ["pebble-rs/gabbro"]
