use std::env;
use std::fs;
use std::path::Path;

fn main() {
    println!("cargo:rerun-if-changed=build/src/message_keys.auto.c");

    println!("cargo:warning=[BUILD.RS] Starting Pebble message key parser...");

    let c_file_path = Path::new("build/src/message_keys.auto.c");

    if !c_file_path.exists() {
        println!("cargo:warning=[BUILD.RS] ERROR: build/src/message_keys.auto.c does not exist!");
        panic!("Missing message_keys.auto.c");
    }

    let content = fs::read_to_string(c_file_path).expect("Failed to read C file");
    let mut generated_code =
        String::from("// Auto-generated by build.rs from message_keys.auto.c\n\n");
    let mut key_count = 0;

    // Parse the C variables
    for line in content.lines() {
        let line = line.trim();
        if line.starts_with("uint32_t MESSAGE_KEY_") {
            let parts: Vec<&str> = line
                .split(&[' ', '=', ';'][..])
                .filter(|s| !s.is_empty())
                .collect();

            if parts.len() >= 3 {
                let key_name = parts[1];
                let key_value = parts[2];

                generated_code.push_str(&format!("pub const {}: u32 = {};\n", key_name, key_value));
                key_count += 1;
            }
        }
    }

    println!(
        "cargo:warning=[BUILD.RS] Successfully parsed {} keys from Pebble!",
        key_count
    );

    let out_dir = env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("message_keys.rs");

    println!(
        "cargo:warning=[BUILD.RS] Saving generated file to: {:?}",
        dest_path
    );

    fs::write(&dest_path, generated_code).expect("Failed to write message_keys.rs");
}
