[package]
name = "bitmap"
version = "0.1.0"
authors = ["RoccoDev <roccodev.business@gmail.com>"]
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
pebble-rs = {path = "../../pebble-rs" }
pebble-sys = {path = "../../pebble-sys" }

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"