[package]
name = "pebble-rs"
version = "0.1.0"
authors = ["RoccoDev <hey@rocco.dev>", "Peatral <contact@peatral.xyz>"]
description = "Pebble bindings for Rust. See repository for instructions."
documentation = "https://docs.rs/pebble-rust"
repository = "https://github.com/pebble-rust/pebble-rust"
readme = "README.md"
keywords = ["pebble", "watch", "cortex", "rebble", "arm"]
categories = ["embedded", "no-std", "hardware-support", "external-ffi-bindings"]
edition = "2024"
license = "GPL-3.0-or-later AND BSD-3-Clause"
include = [
    "src/**/*.rs",
    "Cargo.toml",
]

[badges]
travis-ci = { repository = "pebble-rust/pebble-rust", branch = "master" }

[dependencies]
cty = "0.2.2"
pebble-sys = { path = "../pebble-sys", default-features = false }

[features]
default = ["emery"]

aplite = ["pebble-sys/aplite"]
basalt = ["pebble-sys/basalt"]
chalk = ["pebble-sys/chalk"]
diorite = ["pebble-sys/diorite"]
emery = ["pebble-sys/emery"]
flint = ["pebble-sys/flint"]
gabbro = ["pebble-sys/gabbro"]